
# config/elasticsearch.yml
# development: &default
#   es_bin: '/home/elle/lessons/App/chowmedown/elasticsearch-6.4.0/bin/elasticsearch'
#   host: 'http://localhost:9200'
#   port: '9200'
# test:
#   es_bin: '/home/elle/lessons/App/chowmedown/elasticsearch-6.4.0/bin/elasticsearch'
#   host: 'http://localhost:9250'
#   port: '9250'
# staging:
#   <<: *default
# production:
#   host: ''
#   port: ''s
